server:
  port: 3500

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: PACKING-SERVICE
          uri: lb://PACKING-SERVICE
          predicates:
            - Path=/package/**

        - id: TRANSPORT-SERVICE
          uri: lb://TRANSPORT-SERVICE
          predicates:
            - Path=/transporter/**

        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

eureka:
  instance:
    prefer-Ip-Address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.0.61.145:8761/eureka





